about_me/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from about_me import views

urlpatterns = [
    url(r'^about_me/$', views.about_me, name='about_me'),
]

gallery/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from gallery import views

urlpatterns = [
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^gallery/(?P<gallery_id>\w+)/$', views.galleries, name='galleries'),
]

landing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from landing import views

urlpatterns = [


    url(r'^$', views.landing, name='landing'),
    url(r'^$', views.landing, name='landing'),

]

my_contact/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from my_contact import views

urlpatterns = [
    url(r'^my_contact/$', views.my_contact, name='my_contact'),

]

proksyphoto/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^', include('gallery.urls')),
    url(r'^', include('about_me.urls')),
    url(r'^', include('my_contact.urls')),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models


class GalleryCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категорія галереї'
        verbose_name_plural = 'Категорія галерей'


class Gallery(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(GalleryCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    short_description = models.TextField(blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Галлерея'
        verbose_name_plural = 'Галлереї'


class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='gallery_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотографія'
        verbose_name_plural = 'Фотографії'

landing/models.py
from django.db import models


class Subscriber(models.Model):

    call_number = models.CharField("Номер телефону",max_length=128)
    name = models.CharField("Ім'я", max_length=128)
    message = models.CharField('Повідомлення', max_length=128)
    event_date =models.CharField('Час та дата фотосесії', max_length=128)

    def __str__(self):
        return "Пользователь %s %s" % (self.name, self.call_number,)

    class Meta:
        verbose_name = 'Запит'
        verbose_name_plural = 'Запити на фотосесію'

my_contact/models.py
from django.db import models

gallery/forms.py
from django import forms
from .models import *

# class SubscriberForm(forms.ModelForm):
#
# 	class Meta:
# 		model = Subscriber
# 		exclude = [""]

landing/forms.py
from django import forms
from .models import *


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        exclude = [""]

my_contact/forms.py
from django import forms
from .models import *

about_me/views.py
from django.shortcuts import render
# from .forms import SubscriberForm
from about_me.models import *

def about_me(request):
	# gallery_images = GalleryImage.objects.filter(is_active = True, is_main=True)
	return render(request, 'about_me/about_me.html', locals())

gallery/views.py
from django.shortcuts import render
# from .forms import SubscriberForm
from gallery.models import *

def gallery(request):
	gallery_images = GalleryImage.objects.filter(is_active = True, is_main=True)
	return render(request, 'galleries/gallery.html', locals())




def galleries(request, gallery_id):
    gallery_images = GalleryImage.objects.filter(is_active=True, is_main=True)
    gallery = Gallery.objects.get(id=gallery_id)

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request.session.session_key)

    return render(request, 'galleries/photossession.html', locals())

landing/views.py
from django.shortcuts import render
from .forms import SubscriberForm




def landing(request):
    form = SubscriberForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        print(request.POST)
        print(form.cleaned_data)
        data = form.cleaned_data

        print (data['name'])

        form = form.save()

    return render(request, 'landing/landing.html', locals())

my_contact/views.py
from django.shortcuts import render
# from .forms import SubscriberForm
from my_contact.models import *

def my_contact(request):
	return render(request, 'my_contact/my_contact.html', locals())

templates/about_me/about_me.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{#    <div class="container">#}
{##}
{#        <div class="row">#}
{#            <div class="cell-md-10 cell-lg-8">#}
{#              <p><img src="{% static 'images/about_me_1.jpg' %}" alt="" width="385" height="240">Привіт! Мене звати Ксю, або ж просто Оксана) Бажання творити оточує мене постійно, але саме фотозйомка - це таке заняття, яке сміливо можна віднести до постійних та улюблених.#}
{#                  Люблю щирість та простоту. Бачу в кожному з Вас, щось особливе і намагаюсь під час зйомки ввійти з вами в контакт, щоб фото вийшли дійсно "про особливих вас". Я буду рада зробити для вас красиві, живі та якісні знімки. Пропоную такі формати зйомок: сімейні фотосесії, дитячі,#}
{#                  індивідуальні, lovestory. І пам'ятайте: Кожен момент в житті - важливий!#}
{#              </p>#}
{#            </div>#}
{#        </div>#}
{#        <div class="row">#}
{#            <div class="cell-md-10 cell-lg-8">#}
{#              <p><img class="img-right" src="{% static 'images/3.jpg' %}" alt="" width="770" height="485">Welcome to our wonderful world. We sincerely hope that each and every user entering our website will find exactly what he/she is looking for. With advanced features of activating account and new login widgets, you will definitely have a great experience of using our web page.#}
{#              </p>#}
{#            </div>#}
{#        </div>#}
{##}
{#    </div>#}
<section class="section section-md bg-white">
        <div class="shell">
          <div class="range range-50 range-sm-center range-md-left">
            <div class="cell-sm-6 cell-md-5">
              <div class="thumb-bordered"><img src="{% static 'images/about_me_1.jpg' %}" alt="" width="437" height="435">
              </div>
            </div>
            <div class="cell-sm-6 cell-md-7">
              <div class="box-width-3 box-centered">
                <article class="quote-big">
                  <p class="q">Привіт! Мене звати Ксю, або ж просто Оксана).</p>
                </article>
                <div class="divider"></div>
                <p class="text-spacing-05">Бажання творити оточує мене постійно, але саме фотозйомка - це таке заняття, яке сміливо можна віднести до постійних та улюблених.
                  Люблю щирість та простоту. Бачу в кожному з Вас, щось особливе і намагаюсь під час зйомки ввійти з вами в контакт, щоб фото вийшли дійсно "про особливих вас". Я буду рада зробити для вас красиві, живі та якісні знімки. Пропоную такі формати зйомок: сімейні фотосесії, дитячі,
                  індивідуальні, lovestory. І пам'ятайте: Кожен момент в житті - важливий!</p>
                <div class="group-3-columns" data-lightgallery="group">
                  <div class="column-item"><a class="thumb-light" href="{% static 'images/family.jpg' %}" data-lightgallery="item"><img src="{% static 'images/family.jpg' %}" alt="" width="120" height="171">
                      <div class="thumb-light__overlay"></div></a></div>
                  <div class="column-item"><a class="thumb-light" href="{% static 'images/ind.jpg' %}" data-lightgallery="item"><img src="{% static 'images/ind.jpg' %}" alt="" width="120" height="171">
                      <div class="thumb-light__overlay"></div></a></div>
                  <div class="column-item"><a class="thumb-light" href="{% static 'images/lovestory.jpg' %}" data-lightgallery="item"><img src="{% static 'images/lovestory.jpg' %}" alt="" width="120" height="171">
                      <div class="thumb-light__overlay"></div></a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
  <head>
    <!-- Site Title-->
    <title>Home</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'images/favicon.css' %}">

    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,700,400italic%7CJosefin+Sans:400,700,300italic">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <script src="js/html5shiv.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div id="page-loader">
      <div class="page-loader-body">
        <div class="cssload-spinner">
          <div class="cssload-cube cssload-cube0"></div>
          <div class="cssload-cube cssload-cube1"></div>
          <div class="cssload-cube cssload-cube2"></div>
          <div class="cssload-cube cssload-cube3"></div>
          <div class="cssload-cube cssload-cube4"></div>
          <div class="cssload-cube cssload-cube5"></div>
          <div class="cssload-cube cssload-cube6"></div>
          <div class="cssload-cube cssload-cube7"></div>
          <div class="cssload-cube cssload-cube8"></div>
          <div class="cssload-cube cssload-cube9"></div>
          <div class="cssload-cube cssload-cube10"></div>
          <div class="cssload-cube cssload-cube11"></div>
          <div class="cssload-cube cssload-cube12"></div>
          <div class="cssload-cube cssload-cube13"></div>
          <div class="cssload-cube cssload-cube14"></div>
          <div class="cssload-cube cssload-cube15"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <!-- Page header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="5px" data-lg-stick-up-offset="5px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="/">
                      <div class="brand__name"><img class="brand__logo-dark" src="{% static 'images/logo.png'%}" alt="" width="243" height="57"/><img class="brand__logo-light" src="{% static 'images/logo.png'%}" alt="" width="243" height="57"/>
                      </div></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  <div class="rd-navbar-element">
                    <ul class="list-icons list-inline-sm">
                      <li><a target="_blank" class="icon icon-sm fa fa-instagram icon-style-camera" href="https://www.instagram.com/rivne_photo_bobrovska/"><span></span><span></span><span></span><span></span></a></li>
                      <li><a target="_blank" class="icon icon-sm fa fa-facebook icon-style-camera" href="https://www.facebook.com/profile.php?id=100011105650016"><span></span><span></span><span></span><span></span></a></li>
{#                      <li><a class="icon icon-sm fa fa-pinterest icon-style-camera" href="#"><span></span><span></span><span></span><span></span></a></li>#}
                    </ul>
                  </div>
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li class="active"><a href="{% url 'landing' %}">Home</a>
                    </li>
                    <li><a href="{% url 'about_me' %}">Про мене</a>
                    </li>
                    <li><a href="{% url 'gallery' %}">Портфоліо</a>
                    </li>
{#                    <li><a href="{% url 'my_contact' %}">Мої контакти</a>#}
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
        {% block content %}
        {% endblock content %}


    </div>



      <footer class="footer-centered section bg-gray-darker">
        <div class="shell">
          <div class="range range-sm-center">
            <div class="cell-sm-10 cell-md-8 cell-lg-6">

              <ul class="list-icons list-inline-sm">
                <li><a target="_blank" class="icon icon-sm fa fa-instagram icon-style-camera" href="https://www.instagram.com/rivne_photo_bobrovska/"><span></span><span></span><span></span><span></span></a></li>
                <li><a target="_blank" class="icon icon-sm fa fa-facebook icon-style-camera" href="https://www.facebook.com/profile.php?id=100011105650016"><span></span><span></span><span></span><span></span></a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="{% static 'js/core.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>


    <!-- fancyBox CSS -->
    <link rel="stylesheet" href="{% static 'fancybox/dist/jquery.fancybox.min.css' %}">

    <!-- fancyBox JS -->
    <script src="{% static 'fancybox/dist/jquery.fancybox.min.js' %}"></script>
    <!-- coded by starlight-->

  </body>
</html>

templates/galleries/gallery.html
{% extends 'base.html' %}

{% block content %}

<div class="section section1">
  <div class="container">
    <div class="row">
      {% for gallery_image in gallery_images %}
      <div class="col-lg-3">
        <div class="product-item">
            <a href="{% url 'galleries' gallery_image.gallery.id %}">
              <img src="{{ gallery_image.image.url }}" alt="">
            </a>
            <div>
          </div>
          <h4>{{ gallery_image.gallery.name }}</h4>
          <p>
            {{gallery_image.gallery.description|truncatechars_html:20}}
          </p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>



{% endblock %}

templates/galleries/photossession.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">

            {% for image_item in gallery.galleryimage_set.all %}
                <div class="col-lg-3 col-md-4 col-6 thumb">
                    <div class="product-item">
                        <a data-fancybox="gallery" href="{{ image_item.image.url }}" >
                            <img class="img-fluid" src="{{ image_item.image.url }}" alt="">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/landing/contact_form.html
      <!-- Book Your Photo Shoot-->
      <section class="section section-md bg-white">
        <div class="shell">
          <div class="range range-50 range-sm-center range-md-left range-md-reverse range-md-middle">
            <div class="cell-sm-10 cell-md-6 wow fadeInRight">
              <div class="box-width-4 box-centered">
                <p class="heading-1">Забронюйте <br> Вашу подію</p>
                <p>Щоб замовити фотосесію, будь ласка, внесіть якомога більше деталей щодо вашої конкретної події. Я уточню умови відразу після отримання вашого повідомлення!</p>
              </div>
            </div>
            <div>
             <div class="cell-sm-10 cell-md-6 wow fadeInLeft">
                  <article class="box-line"><span></span><span></span><span></span><span></span>
                    <div class="box-line__main">
                      <form class="rd-mailform" data-form-output="form-output-global" data-form-type="contact" method="POST">{% csrf_token %}
                          <div class="form-group">
                          <input class="form-input" id="contact-date" type="text" data-time-picker="date" name="{{ form.event_date.name }}" data-constraints="@Required">
                          <label class="form-label" for="contact-date">Дата події</label>
                        </div>

                        <div class="form-wrap">
                          <input class="form-input" id="contact-name" type="text" name="{{ form.name.name}}" data-constraints="@Required">
                          <label class="form-label" for="contact-name">Ваше ім'я</label>
                        </div>
                        <div class="form-wrap">
                            <label class="form-label" for="phone">Номер телефону</label>
                          <input class="form-input"  id="phone" name="{{ form.call_number.name}}" data-constraints="@Required">

                        </div>

                        <div class="form-wrap">
                          <label class="form-label" for="contact-message">Ваше повідомлення</label>
                          <textarea class="form-input" id="contact-message" name="{{ form.message.name}}" data-constraints="@Required"></textarea>
                        </div>


                        <div class="form-wrap form-button offset-1">
                          <button class="button button-block button-primary-outline button-ujarak" type="submit">замовити</button>
                        </div>
                      </form>
                    </div>
                  </article>
             </div>
            </div>
          </div>
        </div>
      </section>

templates/landing/landing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <!-- My Best Photos-->
      <section class="section bg-white text-center">
        <!-- Slick Carousel-->
        <div class="slick-wrap">
          <div class="slick-slider slick-style-1" data-arrows="true" data-autoplay="false" data-loop="true" data-dots="true" data-swipe="true" data-xs-swipe="true" data-sm-swipe="false" data-items="1" data-sm-items="3" data-md-items="3" data-lg-items="3" data-center-mode="true" data-lightgallery="group-slick">
            <div class="item">
              <div class="slick-slide-inner">
                <div class="slick-slide-caption"><a class="thumb-ann thumb-mixed_large" href="{% static 'images/slider/1.jpg'%}" data-lightgallery="item"><img class="thumb-ann__image" src="{% static 'images/slider/1.jpg'%}" alt="" width="961" height="664"/>
                    <div class="thumb-ann__caption"> 
                      <p class="thumb-ann__title heading-3">Юлія</p>
                      <p class="thumb-ann__text">Якщо ви шукаєте якісну фотосесію, я буду рада допомогти вам</p>
                    </div></a>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="slick-slide-inner">
                <div class="slick-slide-caption"><a class="thumb-ann thumb-mixed_large" href="{% static 'images/slider/2.jpg'%}" data-lightgallery="item"><img class="thumb-ann__image" src="{% static 'images/slider/2.jpg'%}" alt="" width="961" height="664"/>
                    <div class="thumb-ann__caption"> 
                      <p class="thumb-ann__title heading-3">Олександра</p>
                      <p class="thumb-ann__text">Якщо ви шукаєте якісну фотосесію, я буду рада допомогти вам.</p>
                    </div></a>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="slick-slide-inner">
                <div class="slick-slide-caption"><a class="thumb-ann thumb-mixed_large" href="{% static 'images/slider/3.jpg'%}" data-lightgallery="item"><img class="thumb-ann__image" src="{% static 'images/slider/3.jpg'%}" alt="" width="961" height="664"/>
                    <div class="thumb-ann__caption"> 
                      <p class="thumb-ann__title heading-3">Amanda</p>
                      <p class="thumb-ann__text">Якщо ви шукаєте якісну фотосесію, я буду рада допомогти вам.</p>
                    </div></a>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="slick-slide-inner">
                <div class="slick-slide-caption"><a class="thumb-ann thumb-mixed_large" href="{% static 'images/slider/4.jpg'%}" data-lightgallery="item"><img class="thumb-ann__image" src="{% static 'images/slider/4.jpg'%}" alt="" width="961" height="664"/>
                    <div class="thumb-ann__caption"> 
                      <p class="thumb-ann__title heading-3">Harold &amp; Mary</p>
                      <p class="thumb-ann__text">Якщо ви шукаєте якісну фотосесію, я буду рада допомогти вам.</p>
                    </div></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="section section-md bg-white text-center">
        <div class="shell-fluid">
          <p class="heading-1">Portfolio</p>
          <div class="isotope thumb-ruby-wrap wow fadeIn" data-isotope-layout="masonry" data-isotope-group="gallery" data-lightgallery="group">
            <div class="row">
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item"><a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{% static 'images/1.jpg'%}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'images/1.jpg'%}" alt="" width="440" height="327"/>
                        <div class="thumb-ruby__caption">
                          <p class="thumb-ruby__title heading-3">Христина</p>
                          <p class="thumb-ruby__text">Якщо ви шукаєте якісну фотосесію, я буду рада допомогти вам.
                            <!-- Portfolio-->
                          </p>
                        </div></a>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item"><a class="thumb-ruby thumb-mixed_height-3 thumb-mixed_md" href="{% static 'images/flow.jpg'%}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'images/flow.jpg'%}" alt="" width="444" height="683"/>
                        <div class="thumb-ruby__caption">
                          <p class="thumb-ruby__title heading-3">Kate</p>
                          <p class="thumb-ruby__text">Якщо ви шукаєте якісну фотосесію love, я буду рада допомогти вам.
                            <!-- Portfolio-->
                          </p>
                        </div></a>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item"><a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{% static 'images/book.jpg'%}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'images/book.jpg'%}" alt="" width="440" height="327"/>
                        <div class="thumb-ruby__caption">
                          <p class="thumb-ruby__title heading-3">Аня</p>
                          <p class="thumb-ruby__text">Якщо ви шукаєте якісну фотосесію, я буду рада допомогти вам.
                            <!-- Portfolio-->
                          </p>
                        </div></a>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item"><a class="thumb-ruby thumb-mixed_height-3 thumb-mixed_md" href="{% static 'images/4.jpg'%}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'images/4.jpg'%}" alt="" width="444" height="683"/>
                        <div class="thumb-ruby__caption">
                          <p class="thumb-ruby__title heading-3">Andriy &amp; Kate</p>
                          <p class="thumb-ruby__text">Якщо ви шукаєте якісну фотосесію, я буду рада допомогти вам.
                            <!-- Portfolio-->
                          </p>
                        </div></a>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item"><a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{% static 'images/weeding.jpg' %}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'images/weeding.jpg' %}" alt="" width="440" height="327"/>
                        <div class="thumb-ruby__caption">
                          <p class="thumb-ruby__title heading-3">Яна &amp; Андрій</p>
                          <p class="thumb-ruby__text">Якщо ви шукаєте якісну весільну фотографію, я буду рада допомогти вам
                            <!-- Portfolio-->
                          </p>
                        </div></a>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item"><a class="thumb-ruby thumb-mixed_height-2 thumb-mixed_md" href="{% static 'images/mause.jpg' %}" data-lightgallery="item"><img class="thumb-ruby__image" src="{% static 'images/mause.jpg' %}" alt="" width="440" height="327"/>
                        <div class="thumb-ruby__caption">
                          <p class="thumb-ruby__title heading-3">Lisa</p>
                          <p class="thumb-ruby__text">Якщо ви шукаєте якісну весільну фотографію, я буду рада допомогти вам
                            <!-- Portfolio-->
                          </p>
                        </div></a>
              </div>
            </div>
          </div>
        </div>
      </section>
    {% include 'landing/contact_form.html' %}
{% endblock %}

templates/my_contact/my_contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
          <!-- Get in Touch-->
      {% include 'landing/contact_form.html' %}
{% endblock %}